os: windows
language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - export NODE_ENV=TravisCI
  - dotnet add package Microsoft.Office.Interop.Excel --version 15.0.4795.1000
  - dotnet restore
