os: windows
language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  export NODE_ENV=TravisCI &&
  Install-Package Microsoft.Office.Interop.Excel &&
  dotnet restore &&
